name: 🐛 Bug report
description: Report a bug in the app
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Thank you for taking the time to fill this form!
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: Describe the steps to reproduce this problem
      placeholder: First, click on...
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain the problem in detail
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the app are you using?
      options:
        - 0.0.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: (Optional) Relevant logs
      description: Include any logs that may be relevant
      render: Shell
    validations:
      required: false